2023-07-25 03:27:52,012 - root - INFO - Chat Eugene Popov (ID: 132502896) download file 508.ogg
2023-07-25 03:27:52,023 - TeleBot - ERROR - Infinity polling exception: [WinError 2] Не удается найти указанный файл
2023-07-25 03:27:52,025 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Projects\tg_bots\tg-bot-ya-prac\venv\Lib\site-packages\telebot\__init__.py", line 955, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Projects\tg_bots\tg-bot-ya-prac\venv\Lib\site-packages\telebot\__init__.py", line 1043, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Projects\tg_bots\tg-bot-ya-prac\venv\Lib\site-packages\telebot\__init__.py", line 1118, in __threaded_polling
    raise e
  File "C:\Projects\tg_bots\tg-bot-ya-prac\venv\Lib\site-packages\telebot\__init__.py", line 1074, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Projects\tg_bots\tg-bot-ya-prac\venv\Lib\site-packages\telebot\util.py", line 147, in raise_exceptions
    raise self.exception_info
  File "C:\Projects\tg_bots\tg-bot-ya-prac\venv\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
  File "C:\Projects\tg_bots\tg-bot-ya-prac\venv\Lib\site-packages\telebot\__init__.py", line 6770, in _run_middlewares_and_handler
    result = handler['function'](message)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Projects\tg_bots\tg-bot-ya-prac\app.py", line 58, in get_audio_messages
    converter = Converter(file_name)
                ^^^^^^^^^^^^^^^^^^^^
  File "c:\Projects\tg_bots\tg-bot-ya-prac\converter.py", line 9, in __init__
    subprocess.run(['ffmpeg', '-v', 'quiet', '-i', path_to_file, path_to_file.replace(".ogg", ".wav")])
  File "C:\Users\pohofmd\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pohofmd\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\pohofmd\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1493, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] Не удается найти указанный файл

2023-07-25 03:42:47,399 - TeleBot - ERROR - Infinity polling: polling exited
2023-07-25 03:42:47,401 - TeleBot - ERROR - Break infinity polling
